# Generated by Django 3.1.3 on 2020-11-28 02:59

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', DjangoUeditor.models.UEditorField(verbose_name='回答内容')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='问题名')),
                ('question_text', DjangoUeditor.models.UEditorField(verbose_name='问题内容')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mainapp.article', verbose_name='文章问题')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
