# Generated by Django 3.1.3 on 2020-11-28 02:59

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别')),
                ('desc', models.CharField(max_length=100, verbose_name='类别描述')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章名字')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='文章内容')),
                ('read_num', models.IntegerField(verbose_name='阅读数')),
                ('desc', models.CharField(max_length=100, verbose_name='文章描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mainImg', models.ImageField(default='media/main/img/default.png', upload_to='media/main/img', verbose_name='主图')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mainapp.cate', verbose_name='所属类别')),
            ],
        ),
    ]
