# Generated by Django 3.1.3 on 2020-11-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mainImg',
            field=models.ImageField(default='main/img/default.png', upload_to='main/img', verbose_name='主图'),
        ),
    ]
