# Generated by Django 3.1.3 on 2020-11-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201130_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='aname',
            field=models.CharField(default='新文章', max_length=100, verbose_name='文章名字'),
        ),
        migrations.AlterField(
            model_name='cate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='类别'),
        ),
    ]
