# Generated by Django 3.1.3 on 2020-11-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='headpic',
            field=models.ImageField(default='user/headpic/default.png', upload_to='user/headpic', verbose_name='头像'),
        ),
    ]
